export const WORLD_CENTER_LATITUDE = 35.204111
export const WORLD_CENTER_LONGITUDE = 17.690741

export const MAP_CENTER = [
  WORLD_CENTER_LONGITUDE,
  WORLD_CENTER_LATITUDE,
]

export const MAP_ZOOM = 2
